  
   export const GET_ROOM_DATA='GET_ROOM_DATA';
  export const ADD_ROOM_DATA='ADD_ROOM_DATA';

  export const DELETE_ROOM_DATA='DELETE_ROOM_DATA';

  export const UPDATE_ROOM_DATA='UPDATE_ROOM_DATA';
  export const SINGLE_ROOM_DATA='SINGLE_ROOM_DATA';
